INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000101209159', 'Véritable pâte à tartiner noisettes chocolat noir', 19.62, 'Petit-déjeuners,Produits à tartiner,Produits à tartiner sucrés,Pâtes à tartiner,Pâtes à tartiner aux noisettes,Pâtes à tartiner au chocolat,Pâtes à tartiner aux noisettes et au cacao');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000105000011', 'Lagg''s, chamomile herbal tea', 60.98, 'Plant-based foods and beverages, Beverages, Hot beverages, Plant-based beverages, Teas, Tea bags');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000105000042', 'Lagg''s, herbal tea, peppermint', 92.62, 'Plant-based foods and beverages, Beverages, Hot beverages, Plant-based beverages, Teas, Tea bags');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000105000059', 'Linden Flowers Tea', 8.43, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000105000073', 'Herbal Tea, Hibiscus', 77.14, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000105000196', 'Apple & Cinnamon Tea', 31.72, 'Plant-based foods and beverages, Beverages, Hot beverages, Plant-based beverages, Teas');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000105000219', 'Lagg''s, green tea', 26.88, 'Plant-based foods and beverages, Beverages, Hot beverages, Plant-based beverages, Teas, Green teas, Tea bags');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000105000318', 'Lagg''s, shave grass herbal tea', 6.39, 'Plant-based foods and beverages, Beverages, Hot beverages, Plant-based beverages, Teas, Tea bags');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000105000356', 'Lagg''s, herbal tea, chamomile * mint', 35.62, 'Plant-based foods and beverages, Beverages, Hot beverages, Plant-based beverages, Teas, Tea bags');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000105000363', 'Artichoke Herbal Tea', 35.52, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000105000417', 'Lagg''s, dieter''s herbal tea', 71.77, 'Plant-based foods and beverages, Beverages, Hot beverages, Plant-based beverages, Teas, Tea bags');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000105200923', 'Lagg''s, kidneytea, herbal tea', 97.5, 'Plant-based foods and beverages, Beverages, Hot beverages, Plant-based beverages, Teas, Tea bags');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000105200961', 'Lagg''s, bronchtea', 14.52, 'Plant-based foods and beverages, Beverages, Hot beverages, Plant-based beverages, Teas, Tea bags');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000111048403', '100% Pure Canola Oil', 84.03, 'Plant-based foods and beverages, Plant-based foods, Fats, Vegetable fats, Vegetable oils');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000111301201', 'Original Buttery Spread', 41.97, 'en:Fats');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000111301263', 'Canola harvest, buttery spread, with flaxseed oil', 5.81, 'Fats');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000127534587', 'Today''s temptations, lithuanian rye bread', 99.6, 'Plant-based foods and beverages, Plant-based foods, Cereals and potatoes, Breads');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000130008136', 'Escalope de dinde', 50.96, 'Viandes et dérivés, Viandes, Volailles, Dinde et dérivés, Dindes, Escalopes de dinde');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000140323687', 'Madeleine Framboise', 27.28, 'Snacks, Snacks sucrés, Biscuits et gâteaux, Gâteaux, Madeleines');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000141013129', 'Croissants margarine', 22.74, 'Snacks,Snacks sucrés,en:Sweet pastries and pies,Viennoiseries,Croissants');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000159479269', 'Milkyway, magic stars chocolates', 23.67, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000159487776', 'Milkyway, magic stars chocolates', 69.31, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000168175589', 'Mcvitie''s, digestives cheesecake, lemon', 59.88, 'Snacks, Sweet snacks, Biscuits and cakes, Biscuits');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000168178238', 'Mcvitie''s, mini gingerbread men, milk chocolate', 85.27, 'Snacks, Sweet snacks, Biscuits and cakes, Biscuits');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000171812457', 'Glaces vegetales des alpes', 20.26, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000197571406', 'Puppodums', 88.45, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000204286484', 'Mehrkomponeneten Protein 90 C6 Haselnuß', 80.14, 'Nahrungsergänzungsmittel, Nahrungsergänzungen für Bodybuilder, Proteinpulver');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000208066259', 'Tetley, black tea', 25.04, 'Plant-based foods and beverages, Beverages, Hot beverages, Plant-based beverages, Teas, Black teas, Tea bags');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000209024937', 'The simpsons donuts', 67.95, 'Snacks, Snacks sucrés, Biscuits et gâteaux, Gâteaux, Donuts');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000228000080', 'Terrine de campagne', 4.53, 'Viandes et dérivés, Viandes, Charcuteries, Terrines, Terrines de campagne');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000234022960', 'Croissants pur beurre', 59.1, 'Snacks, Snacks sucrés, Viennoiseries, Croissants, Croissants au beurre');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000236555909', 'Bakers Best, White Bread', 68.29, 'Plant-based foods and beverages, Plant-based foods, Cereals and potatoes, Breads');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000236598784', 'Bakers Best, Rye Bread', 92.1, 'Plant-based foods and beverages, Plant-based foods, Cereals and potatoes, Breads');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000241013128', 'Eclairs', 78.31, 'Snacks, Snacks sucrés, Biscuits et gâteaux, Pâtisseries, Éclairs, Éclairs au chocolat');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000247016406', 'Beignets gourmands parfum choco-noisettes', 89.91, 'Snacks, Snacks sucrés, Biscuits et gâteaux, Gâteaux, Donuts, Beignets fourrés au chocolat');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000250632969', 'Mehrkomponeneten Protein 90 C6 Banane', 16.26, 'Nahrungsergänzungsmittel, Nahrungsergänzungen für Bodybuilder, Proteinpulver');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000260440264', 'Confit d''Oignons ou de figues', 85.63, 'Aliments et boissons à base de végétaux, Aliments d''origine végétale, Condiments, Aliments à base de fruits et de légumes, Produits à tartiner, Plantes condimentaires, Pâtes à tartiner végétales, Produits à tartiner salés, Légumes et dérivés, Oignons et dérivés, Confits d''oignons, en:groceries');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000281621505', 'Warner Hudson, Whisky Chocolates', 88.19, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000281756504', 'Piasten, Chocolate Assortment', 48.71, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000309444901', 'Mt. olive, sweet ''n'' hot salad peppers', 3.69, 'Salted snacks');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000309512075', 'Big Papa''s, Southern Sauce', 40.95, 'Condiments, Sauces, Groceries');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000310413620', 'Lomo de bellota  ibérico 50% raza ibérica', 27.95, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000360053005', 'Cool mint flavor dental gum, cool mint', 16.33, 'Snacks, Sweet snacks, Confectioneries');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000360054002', 'Dental gum', 34.06, 'Snacks, Sweet snacks, Confectioneries, Chewing gum, Sugar-free chewing gum');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000417011002', 'Ritter sport, knusperflakes mit knusprigen cornflakes', 14.61, 'Snacks');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000417012009', 'Rum Trauben Nuss, Milk Chocolate Wih Rum Raisins & Nuts', 96.71, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000417296003', 'Milk Chocolate With Caramelized Almonds', 53.02, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000433070274', 'Funsch, High Quality Marzipan', 63.92, 'Snacks, Sweet snacks, Confectioneries');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000433821494', 'Oatmeal Raisin Cookies', 38.83, 'Snacks, Sweet snacks, Biscuits and cakes, Biscuits');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000433821500', 'The Best Peanut Butter Cookies', 9.71, 'Snacks, Sweet snacks, Biscuits and cakes, Biscuits');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000433906023', 'Best Sweet-Potato Cookies', 80.42, 'Snacks, Sweet snacks, Biscuits and cakes, Biscuits');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000433906030', 'Best Ginger Snap Cookies', 92.89, 'Snacks, Sweet snacks, Biscuits and cakes, Biscuits');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000450193000', 'Lactaid, ice cream, vanilla', 94.82, 'Desserts, Frozen foods, Frozen desserts');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000450193031', 'Lactaid, ice cream, butter pecan', 47.12, 'Desserts, Frozen foods, Frozen desserts');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000460938714', '100% Soja Protein Haselnuss', 74.65, 'Nahrungsergänzungsmittel, Nahrungsergänzungen für Bodybuilder, Proteinpulver');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000470322800', 'Whey Protein aus Molke Vanilla', 89.68, 'Nahrungsergänzungsmittel, Nahrungsergänzungen für Bodybuilder, Proteinpulver');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000501050603', 'Whey Protein aus Molke 1000 Gramm Vanilla', 31.96, 'Nahrungsergänzungsmittel, Nahrungsergänzungen für Bodybuilder, Proteinpulver');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000522061596', 'Salted Sticks & Salted Pretzels', 12.82, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000526938306', 'Whey Protein aus Molke 500 Gramm Vanilla', 13.75, 'Nahrungsergänzungsmittel, Nahrungsergänzungen für Bodybuilder, Proteinpulver');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000539003206', 'Lindt williams, liquor chocolate with williams pear', 6.94, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000554004509', 'Pain de mie sans gluten', 23.47, 'Aliments et boissons à base de végétaux, Aliments d''origine végétale, Céréales et pommes de terre, en:Specific products, en:Products for specific diets, Pains, Produits sans gluten, Pains sans gluten, Pains de mie, Pains de mie sans gluten');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000557910210', 'Flocon d''avoine - complète', 5.24, 'Aliments et boissons à base de végétaux, Aliments d''origine végétale, Petit-déjeuners, Céréales et pommes de terre, Céréales et dérivés, Céréales pour petit-déjeuner, Flocons, Flocons de céréales, Flocons laminés, en:oat-flakes');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000604007221', 'Pain Constance aux céréales', 20.14, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000605013450', 'Le lin', 92.33, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000606009841', 'Beignets framboises', 72.37, 'Snacks, Snacks sucrés, Beignets sucrés');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609124107', 'Solid Milk Chocolate', 63.85, 'Snacks, Sweet snacks, Confectioneries');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609133703', 'Madelaine Chocolate Company, Chocolate', 40.71, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609231508', 'Milk Chocolate Rose', 47.62, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609340767', 'Solid Dark Chocolate', 97.61, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609346752', 'White Chocolate', 50.73, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies, Chocolates, White chocolates');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609406104', 'The Madelaine Chocolate Company, Solid Milk Chocolate Cigars', 95.4, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609407101', 'Madelaine Chocolate, It''s A Girl! Solid Milk Chocolate Cigars, Milk Chocolate', 61.04, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609900114', 'The Madelaine Chocolate Company, All Natural Dark Chocolate Gift Stick', 66.96, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609941001', 'The Madelaine Chocolate Company, Solid Milk Chocolate', 42.32, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609941049', 'The Madelaine Chocolate Company, Solid Dark Chocolate', 89.46, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609941759', 'The madelaine chocolate company, solid milk chocolate', 87.36, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609941766', 'The Madelaine Chocolate Company, Solid Milk Chocolate', 79.37, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609962037', 'Solid Milk Chocolate', 23.02, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609962044', 'The Madelaine Chocolate Company, Solid Dark Chocolate', 30.1, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609962082', 'Solid Dark Chocolate', 49.99, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609965007', 'Milk Chocolate Malt Balls', 48.73, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609983001', 'The Madelaine Chocolate Company, Solid Milk Chocolate', 12.68, 'Snacks, Sweet snacks, Confectioneries');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609983032', 'The Madelaine Chocolate Company, Solid Dark Chocolate', 32.32, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609989010', 'The Madelaine Chocolate Company, Solid Milk Chocolate Bunnies', 11.18, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000609989027', 'The Madelaine Chocolate Company, Solid Milk Chocolate Chicks', 15.85, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000628006569', 'L''Envoûtante (Pain)', 56.82, 'Aliments et boissons à base de végétaux, Aliments d''origine végétale, Céréales et pommes de terre, Pains, Baguettes');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000630135899', 'Spray candy all kidz blend bonus', 49.51, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000630138791', 'Sour & Fruity Candy', 24.78, 'Snacks, Sweet snacks, Confectioneries');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000651003214', 'Romaine Hearts', 42.43, 'Plant-based foods and beverages, Plant-based foods, Fruits and vegetables based foods');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000651041001', 'Romaine lettuce', 16.92, 'Plant-based foods and beverages, Plant-based foods, Fruits and vegetables based foods');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000651041025', 'Green Leaf Lettuce', 49.8, 'Plant-based foods and beverages, Plant-based foods, Fruits and vegetables based foods');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000651213019', 'Fresh Spinach', 86.26, 'Plant-based foods and beverages, Plant-based foods, Fruits and vegetables based foods');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000651213026', 'Cooking Spinach', 67.36, 'Plant-based foods and beverages, Plant-based foods, Fruits and vegetables based foods');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000651319018', 'Quick cook sprout halves, brussels sprouts', 63.01, 'Plant-based foods and beverages, Plant-based foods, Fruits and vegetables based foods');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000651511016', 'Celery', 35.62, 'Plant-based foods and beverages, Plant-based foods, Condiments, Fruits and vegetables based foods, Culinary plants, Vegetables based foods, Vegetable rods, Celery, Groceries');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000651813103', 'Season & Steam Kalettes (Kale Sprouts)', 28.04, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000653007548', 'Baguettine aux olives', 63.97, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000672016408', 'Muffin double chocolat', 23.52, 'Snacks, Snacks sucrés, Biscuits et gâteaux, Gâteaux, Muffins, Gâteaux au chocolat, Muffins au chocolat');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000682009841', 'Pain de campagne bio nature', 42.86, '');
INSERT INTO articles (code_barre, nom, prix, categories) VALUES ('0000698309041', 'Feletti, Pralines Candy, Milk Chocolate', 67.04, 'Snacks, Sweet snacks, Cocoa and its products, Confectioneries, Chocolate candies');
